const NAV=[["inicio","⌂","Visão geral"],["entrevista","◉","Entrevista"],["eem","◇","Estado mental"],["escalas","▤","Escalas"],["seguranca","!","Segurança"],["diagnostico","◎","Diagnóstico"],["farmaco","✚","Psicofármacos"],["plano","✓","Plano"],["evolucao","≡","Evolução"],["referencias","↗","Referências"]];
const interview={"Abertura e queixa":["O que fez você procurar ajuda agora?","Se esta consulta desse certo, o que precisaria estar diferente?","Quando começou? Foi súbito ou gradual? O que estava acontecendo na época?"],"Humor e ansiedade":["Nas últimas semanas, como ficou seu humor, interesse e capacidade de sentir prazer?","Sono, energia, apetite, concentração, culpa, desesperança e psicomotricidade?","Há ansiedade excessiva, crises de pânico, evitação, obsessões/compulsões ou sintomas traumáticos?"],"Bipolaridade antes de antidepressivo":["Já houve período de vários dias com energia ou irritabilidade muito acima do habitual?","Precisou dormir muito menos sem sentir cansaço?","Ficou mais falante, acelerado, confiante, impulsivo, gastando mais ou assumindo riscos?","Alguém percebeu que você estava diferente? Houve prejuízo, internação ou psicose?"],"Psicose e cognição":["Já ouviu/viu coisas que outras pessoas não percebiam?","Sentiu que pessoas, mídia ou acontecimentos tinham mensagens dirigidas a você?","Alguma crença incomum tem causado medo ou mudado seu comportamento?","Orientação, memória, atenção ou funcionamento mudaram de forma aguda/flutuante?"],"Substâncias e medicamentos":["Álcool, nicotina, cannabis, cocaína/estimulantes, sedativos, opioides, energéticos/cafeína? Quantidade, frequência e última utilização?","Medicamentos, suplementos ou hormônios que possam alterar humor/sono?","Já houve abstinência, intoxicação, overdose ou tratamento por uso de substâncias?"],"História longitudinal":["Episódios psiquiátricos prévios, diagnósticos, internações e tentativas de suicídio?","Tratamentos anteriores: o que funcionou, falhou ou causou efeito adverso?","História familiar de bipolaridade, psicose, suicídio, dependência ou resposta medicamentosa?","Desenvolvimento, escolaridade, trabalho, relacionamentos, traumas e funcionamento basal?"],"Clínica geral":["Doenças neurológicas, endócrinas, cardiovasculares, renais/hepáticas, epilepsia, TCE, dor crônica?","Gestação/contracepção/planejamento reprodutivo quando aplicável?","Alergias, medicamentos atuais e adesão?"]};
const mse=["Aparência e autocuidado","Atitude/cooperação","Nível de consciência","Orientação","Atenção","Memória","Psicomotricidade","Fala","Humor subjetivo","Afeto","Curso do pensamento","Conteúdo do pensamento","Percepção","Cognição","Insight","Julgamento crítico"];
const risks=["Ideação de morte/suicídio","Plano definido","Intenção atual","Acesso a meios","Tentativa prévia","Autolesão recente","Psicose com comando","Agitação/impulsividade importante","Heteroagressividade","Intoxicação/abstinência","Mania grave","Delirium/alteração aguda de consciência","Incapacidade de autocuidado","Rede de apoio insuficiente","Fatores protetores identificados"];
const ruleouts=["Mania/hipomania antes de rotular depressão unipolar","Substância/medicamento como causa","Delirium ou condição neurológica aguda","Disfunção tireoidiana/metabólica conforme contexto","Gestação/puerpério quando aplicável","Apneia/privação de sono","TDAH vs ansiedade/humor/trauma","Luto e reação adaptativa vs transtorno","Trauma/PTSD","Condições médicas e interações medicamentosas"];
const nonpharm=["Psicoeducação e decisão compartilhada","Psicoterapia baseada em evidências indicada","Higiene/regularidade do sono","Atividade física conforme condição clínica","Redução de álcool/substâncias","Plano de segurança quando indicado","Envolver rede de apoio com consentimento","Orientar sinais de alarme","Planejar retorno e acesso em piora"];
const monitor=["Peso/IMC e circunferência abdominal quando pertinente","PA e FC","Glicemia/HbA1c e perfil lipídico para antipsicóticos","ECG/QTc quando risco ou fármaco pertinente","Função renal/eletrólitos","TSH","Função hepática","Hemograma quando indicado","Teste de gravidez quando pertinente","Escala-alvo repetida para resposta/remissão","Efeitos adversos, adesão e síndrome de descontinuação"];
const drugs=[
["Sertralina","ISRS","Depressão, ansiedade, TOC/PTSD conforme indicação","25–50 mg/d","50–200 mg/d","Ativação inicial, GI, disfunção sexual, hiponatremia; rastrear bipolaridade."],
["Escitalopram","ISRS","Depressão e ansiedade","5–10 mg/d","10–20 mg/d","QT em contexto de risco/dose, disfunção sexual, hiponatremia; rastrear bipolaridade."],
["Fluoxetina","ISRS","Depressão, TOC, bulimia conforme indicação","10–20 mg/d","20–60 mg/d","Meia-vida longa, ativação/interações CYP2D6; rastrear bipolaridade."],
["Venlafaxina XR","IRSN","Depressão e ansiedade","37,5–75 mg/d","75–225 mg/d","PA, descontinuação, náusea, disfunção sexual."],
["Duloxetina","IRSN","Depressão/ansiedade; dor em indicações específicas","30 mg/d","60–120 mg/d","Náusea, PA; cautela hepática/álcool importante."],
["Bupropiona XL","NDRI","Depressão; cessação tabágica em formulações/indicações próprias","150 mg/d","150–300 mg/d","Evitar em transtorno convulsivo e condições com maior risco de convulsão; pode ativar/insônia."],
["Mirtazapina","NaSSA","Depressão","7,5–15 mg à noite","15–45 mg/d","Sedação, apetite/ganho ponderal."],
["Lítio","Estabilizador","Transtorno bipolar; estratégias de manutenção/augmentação","Individualizar","Por nível sérico/indicação","Janela terapêutica estreita. Antes: renal, eletrólitos, tireoide, interações e gestação quando pertinente. Dosar nível 12 h após dose conforme protocolo."],
["Valproato","Estabilizador/anticonvulsivante","Mania e bipolaridade em cenários selecionados","Individualizar","Por resposta/nível quando usado","Teratogenicidade importante; função hepática, hemograma/plaquetas, peso e interações. Restrições reprodutivas exigem atenção."],
["Lamotrigina","Estabilizador/anticonvulsivante","Bipolaridade, sobretudo prevenção/depressão bipolar conforme contexto","25 mg/d (sem interações relevantes)","Geralmente 100–200 mg/d","Titulação lenta. Rash/SJS; esquemas mudam com valproato e indutores."],
["Quetiapina","Antipsicótico 2ª geração","Esquizofrenia, bipolaridade; depressão em indicações específicas","25–50 mg/d conforme alvo","Varia por indicação","Sedação, hipotensão, peso/metabólico; dose depende fortemente da indicação."],
["Risperidona","Antipsicótico 2ª geração","Psicose/mania conforme indicação","0,5–1 mg/d","2–6 mg/d em muitos cenários","EPS, prolactina, metabólico, hipotensão."],
["Olanzapina","Antipsicótico 2ª geração","Psicose/mania; usos específicos em depressão resistente combinada","2,5–5 mg/d","5–20 mg/d","Alto risco metabólico/ganho ponderal, sedação."],
["Aripiprazol","Antipsicótico 2ª geração","Psicose/mania; augmentação em depressão","2–5 mg/d em augmentação; 10–15 mg/d em psicose/mania","Varia por indicação","Acatisia, ativação, náusea; menor carga metabólica relativa não significa risco zero."],
["Clonazepam","Benzodiazepínico","Uso pontual em indicações selecionadas","0,25–0,5 mg","Individualizar","Sedação, quedas, tolerância/dependência e abstinência; cuidado com álcool/opioides e direção."]
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$("#nav").innerHTML=NAV.map((n,i)=>'<button data-page="'+n[0]+'" class="'+(i?"":"active")+'">'+n[1]+' &nbsp;'+n[2]+'</button>').join("");
function go(id){$$(".page").forEach(x=>x.classList.toggle("active",x.id===id));$$("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));scrollTo(0,0)}
$("#nav").onclick=e=>{if(e.target.dataset.page)go(e.target.dataset.page)}; $$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
$("#interview").innerHTML=Object.entries(interview).map(([h,qs])=>'<div class="section"><h3>'+h+'</h3><div class="sectionbody">'+qs.map(q=>'<label class="prompt"><input type="checkbox"><span>'+q+'</span><textarea placeholder="Notas clínicas..."></textarea></label>').join("")+'</div></div>').join("");
$("#mse").innerHTML=mse.map(x=>'<label class="field">'+x+'<input data-mse="'+x+'" placeholder="Descrever..."></label>').join("");
function checks(id,arr){$(id).innerHTML=arr.map(x=>'<label class="check"><input type="checkbox"><span>'+x+'</span></label>').join("")} checks("#risk",risks);checks("#ruleouts",ruleouts);checks("#nonpharm",nonpharm);checks("#monitor",monitor);
$("#radar").innerHTML=["Queixa e cronologia","Humor/ansiedade","Bipolaridade","Psicose","Substâncias","História prévia/familiar","Clínica/medicações","EEM","Risco suicida/violência","Hipóteses e diferenciais","Plano e follow-up"].map(x=>'<label class="check"><input type="checkbox"><span>'+x+'</span></label>').join("");
const dx=["Depressivo","Bipolar","Ansiedade","Pânico","TOC","Trauma/PTSD","Psicótico","TDAH","Substâncias","Sono","Neurocognitivo","Personalidade","Alimentar","Somático","Adaptativo"];$("#dxchips").innerHTML=dx.map(x=>'<button class="chip">'+x+'</button>').join("");$("#dxchips").onclick=e=>e.target.classList.contains("chip")&&e.target.classList.toggle("on");
$("#fivep").innerHTML=["Predisponentes","Precipitantes","Perpetuadores","Protetores","Apresentação atual","Objetivos do paciente"].map(x=>'<label class="field">'+x+'<textarea></textarea></label>').join("");
function renderDrugs(q=""){let a=drugs.filter(d=>d.join(" ").toLowerCase().includes(q.toLowerCase()));$("#drugs").innerHTML=a.map(d=>'<div class="drug"><small>'+d[1]+'</small><h3>'+d[0]+'</h3><p>'+d[2]+'</p><dl><dt>Início ref.</dt><dd>'+d[3]+'</dd><dt>Faixa ref.</dt><dd>'+d[4]+'</dd><dt>Vigiar</dt><dd>'+d[5]+'</dd></dl><button class="adddrug" data-name="'+d[0]+'">Adicionar ao plano</button></div>').join("")}renderDrugs();$("#drugSearch").oninput=e=>renderDrugs(e.target.value);$("#drugs").onclick=e=>{if(e.target.classList.contains("adddrug")){$("#plantext").value+=($("#plantext").value?"\n":"")+e.target.dataset.name+": ";go("plano")}};
const scaleDefs=[["PHQ-9","Depressão",["Pouco interesse/prazer","Humor deprimido","Sono","Energia","Apetite","Sentir-se mal consigo","Concentração","Lentificação/agitação","Pensamentos de morte/autoagressão"],[0,1,2,3]],["GAD-7","Ansiedade",["Nervoso/ansioso","Não consegue controlar preocupação","Preocupa-se demais","Dificuldade de relaxar","Inquieto","Irritável","Medo de algo ruim"],[0,1,2,3]],["AUDIT-C","Álcool",["Frequência de consumo","Quantidade típica","6+ doses numa ocasião"],[0,1,2,3,4]],["MDQ-mini","Triagem bipolar (não diagnóstica)",["Período de humor/energia anormalmente elevados ou irritáveis","Menor necessidade de sono","Fala/pensamento acelerados","Aumento de atividade/impulsividade","Sintomas ocorreram juntos e causaram mudança/prejuízo"],[0,1]]];
$("#scales").innerHTML=scaleDefs.map((s,i)=>'<div class="card scale" data-scale="'+i+'"><h3>'+s[0]+'</h3><small>'+s[1]+'</small>'+s[2].map((q,j)=>'<label class="field">'+q+'<select data-q="'+j+'>'+s[3].map(v=>'<option value="'+v+'">'+v+'</option>').join("")+'</select></label>').join("")+'<p>Total: <b class="score">0</b></p></div>').join("");$("#scales").onchange=e=>{let c=e.target.closest(".scale");c.querySelector(".score").textContent=[...c.querySelectorAll("select")].reduce((a,x)=>a+ +x.value,0)};
let secs=0,t=null;$("#timerBtn").onclick=()=>{if(t){clearInterval(t);t=null;$("#timerBtn").textContent="Retomar"}else{t=setInterval(()=>{secs++;$("#clock").textContent=String(secs/60|0).padStart(2,"0")+":"+String(secs%60).padStart(2,"0")},1000);$("#timerBtn").textContent="Pausar"}};$("#new").onclick=()=>{if(confirm("Limpar todos os dados desta consulta?")){localStorage.removeItem("psych-os");location.reload()}};
function collectChecked(root){return [...$(root).querySelectorAll("input:checked")].map(x=>x.nextElementSibling?.textContent||"").filter(Boolean)}
$("#generate").onclick=()=>{let mseTxt=mse.map(x=>{let v=document.querySelector('[data-mse="'+x+'"]').value;return v?x+": "+v:null}).filter(Boolean).join("; ");let scales=[...document.querySelectorAll(".scale")].map(x=>x.querySelector("h3").textContent+" "+x.querySelector(".score").textContent).join("; ");let hypotheses=[...document.querySelectorAll(".chip.on")].map(x=>x.textContent).join(", ");let out=`EVOLUÇÃO PSIQUIÁTRICA

QUEIXA / HISTÓRIA ATUAL:
${[...document.querySelectorAll("#interview textarea")].map(x=>x.value.trim()).filter(Boolean).join(" ")||"[completar]"}

EXAME DO ESTADO MENTAL:
${mseTxt||"[completar]"}

RASTREIOS:
${scales}

AVALIAÇÃO DE SEGURANÇA:
Itens presentes/assinalados: ${collectChecked("#risk").join(", ")||"nenhum item assinalado no aplicativo"}. Registrar explicitamente ideação, plano, intenção, meios, tentativas prévias, fatores protetores e julgamento clínico.

HIPÓTESES / FORMULAÇÃO:
${hypotheses||"[completar]"}
${$("#dxnotes").value}

PLANO:
${$("#plantext").value||"[completar]"}
${collectChecked("#nonpharm").length?"Medidas não farmacológicas: "+collectChecked("#nonpharm").join("; ")+".":""}
${collectChecked("#monitor").length?"Monitorização: "+collectChecked("#monitor").join("; ")+".":""}

OBS.: Rastreios são auxiliares e não substituem avaliação diagnóstica. Revisar doses, contraindicações, interações e monitorização antes de finalizar prescrição.`;$("#output").value=out};
$("#copy").onclick=async()=>{await navigator.clipboard.writeText($("#output").value);$("#copy").textContent="Copiado ✓";setTimeout(()=>$("#copy").textContent="Copiar",1200)};$("#print").onclick=()=>window.print();
let save=()=>{let data={inputs:[...document.querySelectorAll("input,textarea,select")].map(x=>({v:x.value,c:x.checked})),chips:[...document.querySelectorAll(".chip")].map(x=>x.classList.contains("on"))};localStorage.setItem("psych-os",JSON.stringify(data))};document.addEventListener("input",save);document.addEventListener("change",save);document.addEventListener("click",e=>{if(e.target.classList.contains("chip"))save()});try{let d=JSON.parse(localStorage.getItem("psych-os"));if(d){[...document.querySelectorAll("input,textarea,select")].forEach((x,i)=>{if(d.inputs[i]){x.value=d.inputs[i].v;x.checked=d.inputs[i].c}});[...document.querySelectorAll(".chip")].forEach((x,i)=>x.classList.toggle("on",!!d.chips[i]));document.querySelectorAll(".scale select").forEach(x=>x.dispatchEvent(new Event("change",{bubbles:true})))}}catch(e){}
